config/routes.rb
Rails.application.routes.draw do
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :members do
    resources :posts, only: [:index]
  end

  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :comments, only: [:create]
  resources :topics, only: [:index, :show]
  resources :notifications, only: [:index]
  resources :statistics, only: [:index]

  root "topics#index"
  get "search" => "search#index"
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts

  class <<self
    def statistic_posts_of_topic
      number_posts_of_topic = Array.new
      color = [
        "#00FFE7", "#FF0018", "#0000FF", "#FFFF00",
        "#008FFF", "#FF7000", "#9100FF", "#6EFF00",
        "#FF00C7", "#00FF38", "#FF004D", "#00FFB2"
      ]
      i = 0
      Topic.all.each do |topic|
        number_post_of_topic = topic.posts.length
        hash = { label: topic.name, value: number_post_of_topic, color: color[i] }
        number_posts_of_topic.push hash
        i += 1
      end
      number_posts_of_topic
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    @posts = @topic.posts.order(last_comment_at: :desc).paginate(page: params[:page])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.haml
.container
  .col-md-9
  .col-md-3
    = form_tag search_path, method: "get", class: "form-inline" do
      .form-group
        = search_field_tag :keyword, "", placeholder: "Search", class: "form-control"
.container
  .panel.panel-primary
    .panel-heading
      %img{ src: asset_path("home.png"), width: "20px", height: "20px" }
      = link_to "Home", root_path, { style: "color:#FFFFFF" }
    .panel-body
      .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %th
          %th
            %center
              Topic
          %th
          %th
            %center
              New Threads / Posts
        %tbody
          - @topics.each do |topic|
            %tr
              %td{ width: "10%" }
                - if topic.name == "C++"
                  %img{ src: asset_path("Cpp.png"), width: "100%" }
                - elsif topic.name == "C#"
                  %img{ src: asset_path("Csharp.png"), width: "100%" }
                - elsif topic.name == ".NET"
                  %img{ src: asset_path("NET.png"), width: "100%" }
                - else
                  %img{ src: asset_path(topic.name + ".png"), width: "100%" }
              %td{ width: "50%" }
                .title
                  %p
                    = link_to topic.name, topic_path(topic.id)
                %br
                = topic.description
              %td{ width: "10%" }
                - number_posts = topic.posts.length
                Number posts of Topic:
                = number_posts
              %td{ width: "30%" }
                - last_post = topic.posts.order(last_comment_at: :desc).first
                - if last_post.present?
                  %img{ src: asset_path("post.png"), width: "20px", height: "20px" }
                  = link_to last_post.title, post_path(last_post.id)
                  %br
                  = "by "
                  = link_to last_post.member.name, member_path(last_post.member.id)
                  %br
                  = last_post.created_at

app/views/topics/show.html.haml
.container
  %p.alignRight
    - if current_member.present? 
      = link_to "New", new_post_path(), method: :get, class: "btn btn-success"
  .panel.panel-primary
    .panel-heading
      %img{ src: asset_path("home.png"), width: "20px", height: "20px" }
      = link_to "Home", root_path, { style: "color:#FFFFFF" }
      = " > "
      = link_to @topic.name, topic_path(@topic.id), { style: "color:#FFFFFF" }
    .panel-body
      - if @posts.length == 0
        %h2
          This topic don't have any post. Create 
          = link_to "New", new_post_path
      - else
        .table-responsive
        %table.table.table-striped.table-hover
          %thead
            %th
            %th
              %center
                Threads / Posts
            %th
              %center
                Comments
            %th
              %center
                Last Activity
          %tbody
            - @posts.each do |post|
              %tr
                %td{ width: "10%" }
                  - if post.status == "closed"
                    %img{ src: asset_path("close.png"), width: "100px", height: "100px" }
                  - else
                    %img{ src: asset_path("open.png"), width: "100px", height: "100px" }
                %td{ width: "50%"}
                  .content
                    %p
                      = link_to post.title, post_path(post.id)
                    = "by "
                    = link_to post.member.name, member_path(post.member.id)
                    = " at "
                    = post.created_at
                %td{ width: "10%"}
                  Comments: 
                  = post.comments.length
                  %br
                  Views:
                  = post.number_views
                  %br
                  Status: 
                  = post.status
                %td{ width: "30%" }
                  - if post.last_comment_id.present?
                    - last_comment = Comment.find_by(id: post.last_comment_id)
                    - if last_comment.present?
                      = link_to last_comment.member.name, member_path(last_comment.member.id)
                      %br
                      = post.last_comment_at
                  - else
                    = link_to post.member.name, member_path(post.member.id)
                    %br
                    = post.last_comment_at
        %center
          = will_paginate @posts