config/routes.rb
Rails.application.routes.draw do
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :members do
    resources :posts, only: [:index]
  end

  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :comments, only: [:create]
  resources :topics, only: [:index, :show]
  resources :notifications, only: [:index]
  resources :statistics, only: [:index]

  root "topics#index"
  get "search" => "search#index"
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains
      = pluralize(object.errors.count, "error")
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_footer.html.haml
.footer
  .container
    %img{ src: asset_path("home_footer_building.png") }

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    .nav
      = link_to "forum", root_path, id: "logo"
      %a{ href: root_path }
        %img.img-circle{ src: asset_path("logo.png"), width: "5%" }
      = link_to "it", root_path, id: "logo"
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home", root_path
        - if logged_in?
          - if current_member.role == "admin"
            %li= link_to "Members", members_path
            %li= link_to "Statistics", statistics_path
          %li= link_to "My posts", member_posts_path(current_member.id)
          - @notifications = member_notification
          - unless @notifications.empty?
            %li
              %a{ href: notifications_path }
                %img{ src: asset_path("notification.png"), alt: "You have some notifications", width: "20px", height: "20px" }
          %li.dropdown.presentation
            %a#statistics.dropdown-toggle{ "aria-expanded": "false",
              "aria-haspopup": "true", "data-toggle": "dropdown",
              "data-target": "#", role: "button" }
              Account
              %span.caret
            %ul.dropdown-menu{ "aria-labelledby": "accounts" }
              %li
                %a{ href: member_path(current_member.id) } Profile
              %li
                %a{ href: edit_member_path(current_member.id) } Settings
              %li.divider
              %li
                = link_to "Log out", logout_path, method: "delete"
        - else
          %li= link_to "Log in", login_path
          %li= link_to "Sign up", new_member_path
.header