config/routes.rb
Rails.application.routes.draw do
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :members do
    resources :posts, only: [:index]
  end

  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :comments, only: [:create]
  resources :topics, only: [:index, :show]
  resources :notifications, only: [:index]
  resources :statistics, only: [:index]

  root "topics#index"
  get "search" => "search#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :member
  belongs_to :topic
  has_many :comments
  has_many :notifications
  validates :title,  presence: true
  validates :content,  presence: true
  validates :member_id,  presence: true
  validates :topic_id,  presence: true

  class << self
    def statistic_post start_date, end_date
      statistic_post = {
        number_post: Array.new,
        date: Array.new
      }
      (start_date..end_date).each do |date|
        number_post = Post.where(
          created_at: date.beginning_of_day..date.end_of_day
        ).count
        statistic_post[:number_post].push number_post
        statistic_post[:date].push date.to_s
      end
      statistic_post
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :must_logged_in, only: [:new, :create, :edit, :update]
  before_action :must_be_admin, only: [:destroy]

  def index
    if(params[:member_id].present?)
      @member = Member.find_by(id: params[:member_id])
      if @member.present?
        @posts = @member.posts.paginate(page: params[:page])
      end
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post.present?
      @comments = @post.comments.paginate(page: params[:page])
      @post.update_attribute(:number_views, @post.number_views+1)
      if current_member.present?
        if current_member.id == @post.member.id
          notifications_post = Notification.where(post_id: @post.id, status: "haven't seen")
          unless notifications_post.empty?
            notifications_post.each do |notification|
              notification.update_attribute(:status, "seen")
            end
          end
        end
      end
    else
      redirect_to root_path
      flash[:danger] = "The post doesn't exist"
    end
  end

  def new
    @post = Post.new
    @topics = Topic.all
  end

  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id
    @post.status = "open"
    @post.number_views = 0
    if @post.save
      redirect_to post_path(@post.id)
      @post.update_attribute(:last_comment_at, @post.created_at)
      flash[:success] = "Success"
    else
      @topics = Topic.all
      render "new"
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    if @post.present?
      unless current_member == @post.member
        redirect_to @post
        flash[:danger] = "Permission denied"
      end
    else
      redirect_to root_path
      flash[:danger] = "The post doesn't exist"
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.present?
      if current_member == @post.member
        if @post.update_attributes(post_params)
          redirect_to @post
          flash[:success] = "Edit successfully"
        else
          render "edit"
        end
      else
        redirect_to @post
        flash[:danger] = "Permission denied"
      end
    else
      redirect_to root_path
      flash[:danger] = "The post doesn't exist"
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.present?
      @post.update_attribute(:status, "closed")
      redirect_to @post
      flash[:success] = "Closed Topic"
    else
      redirect_to root_path
      flash[:danger] = "The post doesn't exist"
    end
  end

  private
    def post_params
      params.require(:post).permit(:topic_id, :title, :content)
    end

    def must_logged_in
      unless logged_in?
        redirect_to login_url
        flash[:danger] = "Please login to continue!"
      end
    end

    def must_be_admin
      if logged_in?
        unless current_member.role == "admin"
          redirect_to current_member
          flash[:danger] = "Permission denied"
        end
      else
        redirect_to login_url
        flash[:danger] = "Please login to continue!"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.haml
.container
  .panel.panel-primary
    .panel-heading
      %h1 Edit Post
    .panel-body
      = form_for @post do |f|
        = render "shared/error_messages", object: f.object
        .form-group
          = f.label :title
          = f.text_field :title, class: "form-control"
        .form-group
          = f.label :content
          = f.text_area :content, class: "tinymce"
          = tinymce
        .button
          = f.submit "Edit", class: "btn btn-primary"

app/views/posts/index.html.haml
.container
  .panel.panel-primary
    .panel-heading
      -if @member.present?
        %h1
          = @member.name + "'s Posts"
    %center
      = will_paginate @posts
    .panel-body
      - if @posts.length == 0
        %h2
          You don't have any post. Create 
          = link_to "new post", new_post_path
      - else
        .table-responsive
        %table.table.table-striped.table-hover
          %thead
            %th Title
          %tbody
            - @posts.each do |post|
              %tr
                %td
                  = link_to post.title, post_path(post.id)
                %td{ width: 120 }
                  = link_to "Edit", edit_post_path(post.id), method: :get, class: "btn btn-success"
      %center
        = will_paginate @posts

app/views/posts/new.html.haml
.container
  .panel.panel-primary
    .panel-heading
      %h1 New Post
    .panel-body
      = form_for @post do |f|
        = render "shared/error_messages", object: f.object
        .form-group
          = f.label :topic
          .form-control
            = f.select(:topic_id) do
              - @topics.each do |topic|
                = content_tag(:option, topic.name, value: topic.id)
        .form-group
          = f.label :title
          = f.text_field :title, class: "form-control"
        .form-group
          = f.label :content
          = f.text_area :content, class: "tinymce"
          = tinymce
        .button
          = f.submit "Post", class: "btn btn-primary"

app/views/posts/show.html.haml
.container
  %p.alignRight
    - if current_member.present? 
      - if current_member == @post.member && @post.status == "open"
        = link_to "Edit", edit_post_path(@post.id), method: :get, class: "btn btn-success"
      - if current_member.role == "admin" && @post.status == "open"
        = link_to "Close", @post, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger"
  .panel.panel-primary
    .panel-heading
      .row
        .col-xs-12.col-md-8
          %img{ src: asset_path("home.png"), width: "20px", height: "20px" }
          = link_to "Home", root_path, { style: "color:#FFFFFF" }
          = " > "
          = link_to @post.topic.name, topic_path(@post.topic.id), { style: "color:#FFFFFF" }
          = " > "
          = link_to @post.title, post_path(@post.id), { style: "color:#FFFFFF" }
        .col-xs-6.col-md-4
          %p.alignRight
            = @post.created_at
    .panel-body
      .table-responsive
      %table.table.table-striped.table-hover
        %td{ width: "100px" }
          %center
            - if @post.member.avatar.url == "/images/original/missing.png"
              %img{ src: asset_path("default_user.png"), width: "100px", height: "100px" }
            - else
              = image_tag @post.member.avatar.url(:thumb)
            %br
            = link_to @post.member.name, @post.member
            - if @post.member.role == "admin"
              %span{ style: "color: red" }
                Admin
        %td
          %h2
            = @post.title
          %br
          = @post.content.html_safe
  - if @comments.present?
    - @comments.each do |comment|
      .panel.panel-primary
        .panel-heading
          = comment.created_at
        .panel-body
          .table-responsive
            %table.table.table-striped.table-hover
              %td{ width: "100px" }
                %center
                  - if comment.member.avatar.url == "/images/original/missing.png"
                    %img{ src: asset_path("default_user.png"), width: "100px", height: "100px" }
                  - else
                    = image_tag comment.member.avatar.url(:thumb)
                  %br
                  = link_to comment.member.name, comment.member
                  - if comment.member.role == "admin"
                    %br
                    %span{ style: "color: red" }
                      = "Admin"
              %td
                = comment.content.html_safe
    %center
      = will_paginate @comments
  - if @post.status == "open" && current_member.present?
    = form_tag({ controller: "comments", action: "create" }, method: "post") do
      = hidden_field_tag(:post_id, @post.id)
      .form-group
        = text_area_tag :content, "", placeholder: "Leave Your Comment", class: "tinymce"
        = tinymce
      .button
        = submit_tag "Comment", class: "btn btn-primary"