config/routes.rb
Rails.application.routes.draw do
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :members do
    resources :posts, only: [:index]
  end

  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :comments, only: [:create]
  resources :topics, only: [:index, :show]
  resources :notifications, only: [:index]
  resources :statistics, only: [:index]

  root "topics#index"
  get "search" => "search#index"
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :avatar
  before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def is_active?
    self.status == "active"
  end

  class << self
    def statistic_member start_date, end_date
      statistic_member = {
        number_member: Array.new,
        date: Array.new
      }
      (start_date..end_date).each do |date|
        number_member = Member.where(
          created_at: date.beginning_of_day..date.end_of_day
        ).count
        statistic_member[:number_member].push number_member
        statistic_member[:date].push date.to_s
      end
      statistic_member
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :must_logged_in, only: [:index, :edit, :update, :destroy]
  before_action :not_logged_in, only: [:new, :create]
  before_action :must_be_admin, only: [:index, :destroy]

  def index
    @members = Member.where(role: nil).paginate(page: params[:page])
  end

  def show
    @member = Member.find_by(id: params[:id])
    if @member.present?
      @number_posts = @member.posts.length
      @number_comments = @member.comments.length
    else
      redirect_to root_path
      flash[:danger] = "Member doesn't exist!"
    end
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    @member.status = "active"
    if @member.save
      redirect_to login_path
      flash[:success] = "Welcome to the forum!"
    else
      render "new"
    end
  end

  def edit
    @member = Member.find_by(id: params[:id])
    if @member.present?
      unless current_member.id == @member.id
        redirect_to root_path
        flash[:danger] = "Permission denied!"
      end
    else
      redirect_to root_path
      flash[:danger] = "Member doesn't exist!"
    end
  end

  def update
    @member = Member.find_by(id: params[:id])
    if @member.present?
       if params[:member].present?
        if current_member.id == @member.id
          if @member.update_attributes(member_params)
            redirect_to @member
            flash[:success] = "Update profile successfully!"
          else
            render "edit"
          end
        else
          redirect_to root_path
          flash[:danger] = "Permission denied!"
        end
      else
        if current_member.role == "admin"
          @member.update_attribute(:role, "admin")
          redirect_to members_path
          flash[:success] = "Success!"
        else
          redirect_to root_path
          flash[:danger] = "Permission denied!"
        end
      end
    else
      redirect_to root_path
      flash[:danger] = "Member doesn't exist!"
    end
  end

  def destroy
    @member = Member.find_by(id: params[:id])
    if @member.present?
      if @member.is_active?
        @member.update_attribute(:status, "deleted")
      else
        @member.update_attribute(:status, "active")
      end
      redirect_to members_path
      flash[:success] = "Success!"
    else
      redirect_to root_path
      flash[:danger] = "Member doesn't exist!"
    end
  end

  private
    def member_params
      params.require(:member).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

    def must_logged_in
      unless logged_in?
        redirect_to login_url
        flash[:danger] = "Please login to continue!"
      end
    end

    def not_logged_in
      if logged_in?
        redirect_to current_member
        flash[:danger] = "You already logged in"
      end
    end

    def must_be_admin
      if logged_in?
        unless current_member.role == "admin"
          redirect_to root_path
          flash[:danger] = "Permission denied!"
        end
      end
    end
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_for(member)
    gravatar_id = Digest::MD5::hexdigest(member.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: member.name, class: "gravatar")
  end
end

app/views/members/edit.html.haml
.container
  .col-md-4.col-md-offset-4
    .panel.panel-primary
      .panel-heading
        %center
          %h1 Update profile
      .panel-body
        = form_for @member do |f|
          = render "shared/error_messages", object: f.object
          .form-group
            = f.label :email
            %br
            = f.text_field :email, class: "form-control"
          .form-group
            = f.label :name
            %br
            = f.text_field  :name, class: "form-control"
          .form-group
            = f.label :password
            %br
            = f.password_field :password, class: "form-control"
          .form-group
            = f.label :password_confirmation
            %br
            = f.password_field :password_confirmation, class: "form-control"
          .form-gruop
            = f.file_field :avatar, class: "form-control"
          .button
            = f.submit "Update your profile", class: "btn btn-primary"

app/views/members/index.html.haml
.container
  .panel.panel-primary
    .panel-heading
      %h1
        All members
    %center
      = will_paginate
    .panel-body
      .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %th ID
          %th Name
          %th Status
          %th Action
        %tbody
          - @members.each do |member|
            %tr
              %td
                = member.id
              %td
                = link_to member.name, member_path(member.id)
              %td
                - if member.is_active?
                  %span{ style: "color: green" }
                    = member.status
                - else
                  %span{ style: "color: red" }
                    = member.status
              %td{ width: 250 }
                = link_to "Be admin", member_path(member.id), method: :put, data: { confirm: "You sure?" } ,class: "btn btn-warning"
                - if member.is_active?
                  = link_to "Delete", member, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger"
                - else
                  = link_to "Active", member, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-success"
    %center
      = will_paginate

app/views/members/new.html.haml
.container
  .col-md-4.col-md-offset-4
    .panel.panel-primary
      .panel-heading
        %center
          %h1 Sign up
      .panel-body
        = form_for @member do |f|
          = render "shared/error_messages", object: f.object
          .form-group
            = f.label :email
            %br
            = f.text_field :email, class: "form-control"
          .form-group
            = f.label :name
            %br
            = f.text_field  :name, class: "form-control"
          .form-group
            = f.label :password
            %br
            = f.password_field :password, class: "form-control"
          .form-group
            = f.label :password_confirmation
            %br
            = f.password_field :password_confirmation, class: "form-control"
          .button
            = f.submit "Sign Up", class: "btn btn-primary"

app/views/members/show.html.haml
.container
  .row
    .panel.panel-primary
      .panel-heading
        %h1
          %center
            Member Information
      .panel-body
        .col-md-3
          - if @member.avatar.url == "/images/original/missing.png"
            %img{ src: asset_path("default_user.png"), width: "300px", height: "300px" }
          - else
            = image_tag @member.avatar.url(:medium)
        .col-md-6
          .show-text
            %span
              Name:
            = @member.name
            %br
            %span
              Email:
            = @member.email
            %br
            %span
              Joined at:
            = @member.created_at.to_date
            %br
            %span
              Number of posts:
            = @number_posts
            %br
            %span
              Number of comments:
            = @number_comments
            %br
            - if logged_in? && current_member.id == @member.id
              .button
                = link_to "Edit your profile", edit_member_path(@member.id), method: :get, class: "btn btn-success"